/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CpuInfo: typeof import('./src/components/HardwareInformation/CpuInfo.vue')['default']
    DiskInfo: typeof import('./src/components/HardwareInformation/DiskInfo.vue')['default']
    GpuInfo: typeof import('./src/components/HardwareInformation/GpuInfo.vue')['default']
    HardwareInformation: typeof import('./src/components/HardwareInformation/index.vue')['default']
    LinkItem: typeof import('./src/components/LinkList/components/LinkItem.vue')['default']
    LinkList: typeof import('./src/components/LinkList/index.vue')['default']
    LinkUpsertModal: typeof import('./src/components/LinkUpsertModal/index.vue')['default']
    MemoryInfo: typeof import('./src/components/HardwareInformation/MemoryInfo.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NetworkInfo: typeof import('./src/components/HardwareInformation/NetworkInfo.vue')['default']
    NFlex: typeof import('naive-ui')['NFlex']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NInputGroupLabel: typeof import('naive-ui')['NInputGroupLabel']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPopover: typeof import('naive-ui')['NPopover']
    NProgress: typeof import('naive-ui')['NProgress']
    NText: typeof import('naive-ui')['NText']
    PopoverButton: typeof import('./src/components/PopoverButton/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusDot: typeof import('./src/components/LinkList/components/StatusDot.vue')['default']
    'Term.vue': typeof import('./src/components/Term.vue/index.vue')['default']
  }
}
